export interface CuteCard {
  id: string;
  name: string;
  roleLabel: string;
  gender: "GROOM" | "BRIDE" | "BOTH";
  personality: string;
  quote: string;
  emoji: string;
  theme: {
    bgGradient: string;
    border: string;
    accent: string;
    badgeBg: string;
    badgeText: string;
    glow: string;
  };
}

export const CUTE_CARDS: CuteCard[] = [
  // --- CALON SUAMI (GROOM) ---
  {
    id: "cat-prince",
    name: "Pangeran Miaw",
    roleLabel: "Calon Suami Penyayang",
    gender: "GROOM",
    personality: "Setia & Penuh Perhatian",
    quote: "Siap menjagamu dan membahagiakanmu setiap hari!",
    emoji: "🐱👑",
    theme: {
      bgGradient: "from-sky-50 via-blue-50 to-indigo-50",
      border: "border-sky-300",
      accent: "text-sky-600",
      badgeBg: "bg-sky-500",
      badgeText: "text-white",
      glow: "shadow-sky-100",
    },
  },
  {
    id: "bear-groom",
    name: "Ksatria Teddy",
    roleLabel: "Calon Suami Pengayom",
    gender: "GROOM",
    personality: "Tangguh & Pelindung",
    quote: "Bersamamu, rumah tangga kita kokoh dan penuh ketenangan.",
    emoji: "🐻🛡️",
    theme: {
      bgGradient: "from-amber-50 via-orange-50 to-amber-100",
      border: "border-amber-300",
      accent: "text-amber-700",
      badgeBg: "bg-amber-600",
      badgeText: "text-white",
      glow: "shadow-amber-100",
    },
  },
  {
    id: "penguin-groom",
    name: "Pinguin Romeo",
    roleLabel: "Calon Suami Romantis",
    gender: "GROOM",
    personality: "Setia Seumur Hidup",
    quote: "Seperti pinguin, aku memilihmu untuk selamanya.",
    emoji: "🐧💍",
    theme: {
      bgGradient: "from-cyan-50 via-teal-50 to-blue-50",
      border: "border-cyan-300",
      accent: "text-cyan-700",
      badgeBg: "bg-cyan-600",
      badgeText: "text-white",
      glow: "shadow-cyan-100",
    },
  },
  {
    id: "fox-groom",
    name: "Rubah Koko",
    roleLabel: "Calon Suami Cerdas",
    gender: "GROOM",
    personality: "Perencana Finansial Handal",
    quote: "Target tabungan aman, masa depan kita terencana rapi!",
    emoji: "🦊💼",
    theme: {
      bgGradient: "from-orange-50 via-amber-50 to-yellow-50",
      border: "border-orange-300",
      accent: "text-orange-700",
      badgeBg: "bg-orange-500",
      badgeText: "text-white",
      glow: "shadow-orange-100",
    },
  },
  {
    id: "panda-groom",
    name: "Panda Boba",
    roleLabel: "Calon Suami Kalem",
    gender: "GROOM",
    personality: "Sabar & Menyenangkan",
    quote: "Santai tapi pasti, hajatan kita beres tanpa pusing!",
    emoji: "🐼🎋",
    theme: {
      bgGradient: "from-slate-50 via-zinc-50 to-teal-50",
      border: "border-slate-300",
      accent: "text-slate-700",
      badgeBg: "bg-slate-700",
      badgeText: "text-white",
      glow: "shadow-slate-100",
    },
  },
  {
    id: "lion-groom",
    name: "Singa Sultan",
    roleLabel: "Calon Suami Pemimpin",
    gender: "GROOM",
    personality: "Wibawa & Penuh Tanggung Jawab",
    quote: "Memimpin bahtera keluarga dengan ridho dan kehangatan.",
    emoji: "🦁👑",
    theme: {
      bgGradient: "from-yellow-50 via-amber-50 to-orange-50",
      border: "border-yellow-400",
      accent: "text-yellow-800",
      badgeBg: "bg-amber-600",
      badgeText: "text-white",
      glow: "shadow-amber-100",
    },
  },
  {
    id: "shiba-groom",
    name: "Shiba Taro",
    roleLabel: "Calon Suami Setia",
    gender: "GROOM",
    personality: "Pekerja Keras & Ceria",
    quote: "Selalu bersemangat membina masa depan manis berdua.",
    emoji: "🐕💼",
    theme: {
      bgGradient: "from-amber-50 via-stone-50 to-yellow-50",
      border: "border-amber-300",
      accent: "text-amber-800",
      badgeBg: "bg-amber-700",
      badgeText: "text-white",
      glow: "shadow-amber-100",
    },
  },
  {
    id: "koala-groom",
    name: "Koala Koko",
    roleLabel: "Calon Suami Lembut",
    gender: "GROOM",
    personality: "Hangat & Pendengar Setia",
    quote: "Rumah kita akan jadi tempat paling damai untuk pulang.",
    emoji: "🐨🌿",
    theme: {
      bgGradient: "from-emerald-50 via-teal-50 to-slate-50",
      border: "border-emerald-300",
      accent: "text-emerald-700",
      badgeBg: "bg-emerald-600",
      badgeText: "text-white",
      glow: "shadow-emerald-100",
    },
  },
  {
    id: "dolphin-groom",
    name: "Lumba Ocean",
    roleLabel: "Calon Suami Ceria",
    gender: "GROOM",
    personality: "Humoris & Menghibur",
    quote: "Setiap hari bersamamu selalu penuh tawa dan senyuman!",
    emoji: "🐬🌊",
    theme: {
      bgGradient: "from-blue-50 via-sky-50 to-cyan-50",
      border: "border-blue-300",
      accent: "text-blue-700",
      badgeBg: "bg-blue-600",
      badgeText: "text-white",
      glow: "shadow-blue-100",
    },
  },
  {
    id: "elephant-groom",
    name: "Gajah Gani",
    roleLabel: "Calon Suami Bijaksana",
    gender: "GROOM",
    personality: "Dewasa & Dermawan",
    quote: "Kesabaran dan keikhlasan adalah pondasi keluarga kita.",
    emoji: "🐘💐",
    theme: {
      bgGradient: "from-indigo-50 via-slate-50 to-blue-50",
      border: "border-indigo-300",
      accent: "text-indigo-700",
      badgeBg: "bg-indigo-600",
      badgeText: "text-white",
      glow: "shadow-indigo-100",
    },
  },
  {
    id: "otter-groom",
    name: "Berang Boni",
    roleLabel: "Calon Suami Kompak",
    gender: "GROOM",
    personality: "Kolaboratif & Mesra",
    quote: "Bergandengan tangan menghadapi lika-liku kehidupan berdua.",
    emoji: "🦦🫧",
    theme: {
      bgGradient: "from-teal-50 via-emerald-50 to-cyan-50",
      border: "border-teal-300",
      accent: "text-teal-700",
      badgeBg: "bg-teal-600",
      badgeText: "text-white",
      glow: "shadow-teal-100",
    },
  },
  {
    id: "tiger-groom",
    name: "Harimau Raka",
    roleLabel: "Calon Suami Pelindung",
    gender: "GROOM",
    personality: "Berani & Berprinsip",
    quote: "Menjaga kehormatan keluarga dan setia lahir batin.",
    emoji: "🐯⚡",
    theme: {
      bgGradient: "from-orange-50 via-red-50 to-amber-50",
      border: "border-orange-400",
      accent: "text-orange-800",
      badgeBg: "bg-orange-600",
      badgeText: "text-white",
      glow: "shadow-orange-100",
    },
  },
  {
    id: "squirrel-groom",
    name: "Tupai Tito",
    roleLabel: "Calon Suami Cekatan",
    gender: "GROOM",
    personality: "Lincah & Sigap",
    quote: "Semua urusan berkas KUA dan vendor tuntas tanpa drama!",
    emoji: "🐿️🌰",
    theme: {
      bgGradient: "from-amber-50 via-yellow-50 to-orange-50",
      border: "border-amber-300",
      accent: "text-amber-800",
      badgeBg: "bg-amber-600",
      badgeText: "text-white",
      glow: "shadow-amber-100",
    },
  },

  // --- CALON ISTRI (BRIDE) ---
  {
    id: "cat-princess",
    name: "Permaisuri Luna",
    roleLabel: "Calon Istri Anggun",
    gender: "BRIDE",
    personality: "Ceria & Lemah Lembut",
    quote: "Biar hajatan kita makin manis, terarah & berkah!",
    emoji: "🐱🌸",
    theme: {
      bgGradient: "from-pink-50 via-rose-50 to-amber-50",
      border: "border-rose-300",
      accent: "text-rose-600",
      badgeBg: "bg-rose-500",
      badgeText: "text-white",
      glow: "shadow-rose-100",
    },
  },
  {
    id: "bunny-bride",
    name: "Kelinci Mochi",
    roleLabel: "Calon Istri Gemoy",
    gender: "BRIDE",
    personality: "Kreatif & Bersemangat",
    quote: "Semua detail pernikahan kita siapkan dengan cinta!",
    emoji: "🐰🎀",
    theme: {
      bgGradient: "from-fuchsia-50 via-pink-50 to-purple-50",
      border: "border-pink-300",
      accent: "text-fuchsia-600",
      badgeBg: "bg-fuchsia-500",
      badgeText: "text-white",
      glow: "shadow-pink-100",
    },
  },
  {
    id: "deer-bride",
    name: "Rusa Bella",
    roleLabel: "Calon Istri Bijak",
    gender: "BRIDE",
    personality: "Bijaksana & Tenang",
    quote: "Membangun surga kecil di rumah kita bersama.",
    emoji: "🦌✨",
    theme: {
      bgGradient: "from-emerald-50 via-teal-50 to-lime-50",
      border: "border-emerald-300",
      accent: "text-emerald-700",
      badgeBg: "bg-emerald-600",
      badgeText: "text-white",
      glow: "shadow-emerald-100",
    },
  },
  {
    id: "duck-bride",
    name: "Bebek Cici",
    roleLabel: "Calon Istri Ramah",
    gender: "BRIDE",
    personality: "Ramah & Hangat",
    quote: "Menyambut hari bahagia dengan senyuman paling manis!",
    emoji: "🐥🌼",
    theme: {
      bgGradient: "from-yellow-50 via-amber-50 to-orange-50",
      border: "border-yellow-300",
      accent: "text-yellow-700",
      badgeBg: "bg-amber-500",
      badgeText: "text-white",
      glow: "shadow-yellow-100",
    },
  },
  {
    id: "hedgehog-bride",
    name: "Landak Pipit",
    roleLabel: "Calon Istri Teliti",
    gender: "BRIDE",
    personality: "Detail & Peduli Sesama",
    quote: "Checklist rapi, akad khidmat, resepsi berkesan!",
    emoji: "🦔🌷",
    theme: {
      bgGradient: "from-violet-50 via-purple-50 to-pink-50",
      border: "border-violet-300",
      accent: "text-violet-700",
      badgeBg: "bg-violet-600",
      badgeText: "text-white",
      glow: "shadow-violet-100",
    },
  },
  {
    id: "swan-bride",
    name: "Angsa Seraphina",
    roleLabel: "Calon Istri Tulus",
    gender: "BRIDE",
    personality: "Anggun & Tulus Sejati",
    quote: "Cinta sejati berlabuh dalam janji suci akad nikah.",
    emoji: "🦢🤍",
    theme: {
      bgGradient: "from-slate-50 via-rose-50 to-sky-50",
      border: "border-rose-200",
      accent: "text-rose-700",
      badgeBg: "bg-rose-400",
      badgeText: "text-white",
      glow: "shadow-rose-100",
    },
  },
  {
    id: "butterfly-bride",
    name: "Kupu Mariposa",
    roleLabel: "Calon Istri Menawan",
    gender: "BRIDE",
    personality: "Penuh Harapan & Ceria",
    quote: "Mekar bersama menggapai impian masa depan indah.",
    emoji: "🦋✨",
    theme: {
      bgGradient: "from-purple-50 via-indigo-50 to-pink-50",
      border: "border-purple-300",
      accent: "text-purple-700",
      badgeBg: "bg-purple-600",
      badgeText: "text-white",
      glow: "shadow-purple-100",
    },
  },
  {
    id: "hamster-bride",
    name: "Hamster Himi",
    roleLabel: "Calon Istri Gemas",
    gender: "BRIDE",
    personality: "Cermat & Menggemaskan",
    quote: "Pos tabungan aman, belanja seserahan tepat sasaran!",
    emoji: "🐹🌻",
    theme: {
      bgGradient: "from-amber-50 via-yellow-50 to-rose-50",
      border: "border-amber-300",
      accent: "text-amber-700",
      badgeBg: "bg-amber-500",
      badgeText: "text-white",
      glow: "shadow-amber-100",
    },
  },
  {
    id: "flamingo-bride",
    name: "Flamingo Fifi",
    roleLabel: "Calon Istri Modis",
    gender: "BRIDE",
    personality: "Percaya Diri & Estetik",
    quote: "Dekorasi pelaminan dan gaun akad tampil menawan!",
    emoji: "🦩🌺",
    theme: {
      bgGradient: "from-rose-50 via-pink-50 to-fuchsia-50",
      border: "border-rose-300",
      accent: "text-rose-700",
      badgeBg: "bg-rose-600",
      badgeText: "text-white",
      glow: "shadow-rose-100",
    },
  },
  {
    id: "dove-bride",
    name: "Merpati Murni",
    roleLabel: "Calon Istri Khidmat",
    gender: "BRIDE",
    personality: "Damai & Penyejuk Jiwa",
    quote: "Semoga langkah sakral kita selalu dinaungi keberkahan.",
    emoji: "🕊️💍",
    theme: {
      bgGradient: "from-teal-50 via-cyan-50 to-blue-50",
      border: "border-teal-300",
      accent: "text-teal-700",
      badgeBg: "bg-teal-600",
      badgeText: "text-white",
      glow: "shadow-teal-100",
    },
  },
  {
    id: "angora-bride",
    name: "Anggora Chloe",
    roleLabel: "Calon Istri Manja",
    gender: "BRIDE",
    personality: "Lembut & Penuh Manja",
    quote: "Siap jadi teman hidup terbaik sepanjang usia.",
    emoji: "🐈‍⬛💎",
    theme: {
      bgGradient: "from-fuchsia-50 via-purple-50 to-indigo-50",
      border: "border-fuchsia-300",
      accent: "text-fuchsia-700",
      badgeBg: "bg-fuchsia-600",
      badgeText: "text-white",
      glow: "shadow-fuchsia-100",
    },
  },
  {
    id: "panda-pink-bride",
    name: "Panda Mei",
    roleLabel: "Calon Istri Penyayang",
    gender: "BRIDE",
    personality: "Sabar & Perhatian",
    quote: "Menemani langkahmu dalam suka maupun duka berdua.",
    emoji: "🐼🌸",
    theme: {
      bgGradient: "from-pink-50 via-rose-50 to-purple-50",
      border: "border-pink-300",
      accent: "text-pink-700",
      badgeBg: "bg-pink-500",
      badgeText: "text-white",
      glow: "shadow-pink-100",
    },
  },
  {
    id: "fox-bride",
    name: "Rubah Ruby",
    roleLabel: "Calon Istri Cermat",
    gender: "BRIDE",
    personality: "Teliti & Perencana Ulung",
    quote: "Daftar vendor aman dan rundown hari H terkendali!",
    emoji: "🦊🌸",
    theme: {
      bgGradient: "from-orange-50 via-rose-50 to-amber-50",
      border: "border-orange-300",
      accent: "text-orange-700",
      badgeBg: "bg-orange-500",
      badgeText: "text-white",
      glow: "shadow-orange-100",
    },
  },
];

export function getCuteCard(id?: string): CuteCard {
  const found = CUTE_CARDS.find((c) => c.id === id);
  return found || CUTE_CARDS[0];
}

export function getDefaultCuteCardForRole(role?: "GROOM" | "BRIDE" | "COLLABORATOR"): CuteCard {
  if (role === "BRIDE") return CUTE_CARDS.find((c) => c.id === "cat-princess") || CUTE_CARDS[13];
  return CUTE_CARDS[0]; // Pangeran Miaw
}
