import {
  WeddingProject,
  SavingContribution,
  ChecklistItem,
  SeserahanItem,
  PostWeddingItem,
  GuestItem,
  ActivityLog,
  RundownItem,
  FamilyQuota,
} from "@/types";

export const mockWedding: WeddingProject = {
  id: "w-1",
  title: "Pernikahan Heru & Nurul",
  groomName: "Muhammad Heru",
  brideName: "Nurul Fathonah",
  weddingDate: "2026-12-19T08:00:00Z",
  city: "Bandung, Jawa Barat",
  targetBudget: 120000000,
  currentSavings: 82500000,
  inviteCode: "HAJAT-89X2",
  slug: "heru-nurul",
  isPartnerConnected: true,
  partnerInfo: {
    name: "Nurul Fathonah",
    role: "BRIDE",
    email: "nurul.fathonah@gmail.com",
    image: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
  },
};

export const mockSavingContributions: SavingContribution[] = [
  { label: "Tabungan Heru (Suami)", amount: 46000000, percentage: 55.8, color: "#38BDF8" }, // Pastel Sky 400
  { label: "Tabungan Nurul (Istri)", amount: 28500000, percentage: 34.5, color: "#7DD3FC" }, // Pastel Sky 300
  { label: "Bantuan Hibah Keluarga", amount: 8000000, percentage: 9.7, color: "#BAE6FD" }, // Pastel Sky 200
];

export const mockActivityLogs: ActivityLog[] = [
  {
    id: "act-1",
    userName: "Nurul Fathonah",
    userRole: "BRIDE",
    action: "Menambahkan Mukena Sutra Royale Premium ke Box 1 Seserahan",
    timeAgo: "10 menit yang lalu",
  },
  {
    id: "act-2",
    userName: "Muhammad Heru",
    userRole: "GROOM",
    action: "Menyetor tabungan bersama sebesar Rp 5.000.000",
    timeAgo: "2 jam yang lalu",
  },
  {
    id: "act-3",
    userName: "Nurul Fathonah",
    userRole: "BRIDE",
    action: "Mencentang selesai: Tes Kesehatan Catin di Puskesmas & Elsimil",
    timeAgo: "Kemarin",
  },
  {
    id: "act-4",
    userName: "Muhammad Heru",
    userRole: "GROOM",
    action: "Memasukkan rincian Kulkas 2 Pintu LG ke Wishlist Pasca-Nikah",
    timeAgo: "2 hari yang lalu",
  },
];

export const mockChecklist: ChecklistItem[] = [
  {
    id: "chk-1",
    title: "Pengurusan Surat Pengantar RT/RW & Kelurahan (N1, N2, N4)",
    description: "Membawa fotokopi KTP, KK, dan Akta Kelahiran kedua calon mempelai ke Kelurahan domisili.",
    category: "ADMINISTRASI_KUA",
    timelineTag: "H-3 Bulan",
    status: "COMPLETED",
    assignedTo: "Heru (Suami)",
    isOfficialKUA: true,
  },
  {
    id: "chk-2",
    title: "Pemeriksaan Kesehatan Catin Puskesmas & Sertifikat Elsimil",
    description: "Cek Hb, golongan darah, imunisasi TT untuk calon istri, dan download sertifikat Elsimil BKKBN.",
    category: "ADMINISTRASI_KUA",
    timelineTag: "H-3 Bulan",
    status: "COMPLETED",
    assignedTo: "Nurul (Istri)",
    isOfficialKUA: true,
  },
  {
    id: "chk-3",
    title: "Pendaftaran Online SIMKAH Kemenag & Kode Billing PNBP",
    description: "Daftar di simkah4.kemenag.go.id, upload pas foto latar biru (2x3 & 4x6), dan bayar PNBP Rp 600rb jika nikah weekend.",
    category: "ADMINISTRASI_KUA",
    timelineTag: "H-2 Bulan",
    status: "IN_PROGRESS",
    assignedTo: "Bersama",
    isOfficialKUA: true,
  },
  {
    id: "chk-4",
    title: "Bimbingan Perkawinan (Bimwin) Mandiri / KUA",
    description: "Mengikuti kursus bimbingan pranikah 2 hari di KUA setempat.",
    category: "ADMINISTRASI_KUA",
    timelineTag: "H-1 Bulan",
    status: "TODO",
    assignedTo: "Bersama",
    isOfficialKUA: true,
  },
  {
    id: "chk-5",
    title: "Finalisasi Booking Venue & Katering (DP 30%)",
    description: "Uji rasa katering (food testing) 6 varian gubukan dan lock tanggal gedung.",
    category: "VENUE_CATERING",
    timelineTag: "H-6 Bulan",
    status: "COMPLETED",
    assignedTo: "Bersama",
  },
  {
    id: "chk-6",
    title: "Fitting Pertama Busana Akad & Resepsi",
    description: "Fitting kebaya adat Sunda siger untuk Nurul dan beskap pengantin untuk Heru.",
    category: "BUSANA_MUA",
    timelineTag: "H-2 Bulan",
    status: "IN_PROGRESS",
    assignedTo: "Nurul (Istri)",
  },
  {
    id: "chk-7",
    title: "Pesan Souvenir Pernikahan & Cetak Undangan Fisik VIP",
    description: "Souvenir pouch kulit sintetis 500 pcs & 50 undangan hard cover untuk keluarga inti.",
    category: "UNDANGAN_SOUVENIR",
    timelineTag: "H-2 Bulan",
    status: "TODO",
    assignedTo: "Heru (Suami)",
  },
];

export const mockSeserahanItems: SeserahanItem[] = [
  {
    id: "ses-1",
    boxNumber: 1,
    boxName: "Box 1: Perlengkapan Ibadah",
    name: "Set Mukena Silk Premium & Sajadah",
    brand: "Royale Premium Silk",
    category: "Ibadah",
    estimatedPrice: 1250000,
    actualPrice: 1150000,
    purchaseUrl: "https://shopee.co.id/search?keyword=mukena+royale+premium",
    isPurchased: true,
    notes: "Warna Rose Gold Soft, bordir renda keliling",
  },
  {
    id: "ses-2",
    boxNumber: 1,
    boxName: "Box 1: Perlengkapan Ibadah",
    name: "Al-Qur'an Terjemahan Tajwid Pelangi",
    brand: "Madina Al-Qur'an",
    category: "Ibadah",
    estimatedPrice: 280000,
    actualPrice: 260000,
    purchaseUrl: "https://tokopedia.com/search?q=alquran+madina",
    isPurchased: true,
    notes: "Cover beludru senada mukena",
  },
  {
    id: "ses-3",
    boxNumber: 2,
    boxName: "Box 2: Skincare & Body Care",
    name: "Crystallure Supreme Revitalizing Set",
    brand: "Wardah Crystallure",
    category: "Perawatan Wajah",
    estimatedPrice: 1400000,
    actualPrice: 1350000,
    purchaseUrl: "https://shopee.co.id/wardahofficial",
    isPurchased: true,
    notes: "Lengkap dengan essence, serum, cream",
  },
  {
    id: "ses-4",
    boxNumber: 2,
    boxName: "Box 2: Skincare & Body Care",
    name: "Parfum Miss Dior Blooming Bouquet 100ml",
    brand: "Dior",
    category: "Parfum",
    estimatedPrice: 2600000,
    purchaseUrl: "https://sephora.co.id/products/dior-miss-dior",
    isPurchased: false,
    notes: "Beli di gerai resmi Sephora",
  },
  {
    id: "ses-5",
    boxNumber: 3,
    boxName: "Box 3: Tas & Sepatu",
    name: "Metallic Push-Lock Shoulder Bag",
    brand: "Charles & Keith",
    category: "Aksesoris",
    estimatedPrice: 1199000,
    purchaseUrl: "https://charleskeith.co.id",
    isPurchased: false,
    notes: "Warna Cream / Nude",
  },
  {
    id: "ses-6",
    boxNumber: 3,
    boxName: "Box 3: Tas & Sepatu",
    name: "Pointed Toe Block Heels 5cm",
    brand: "VAIA Official",
    category: "Sepatu",
    estimatedPrice: 850000,
    actualPrice: 820000,
    purchaseUrl: "https://tokopedia.com/vaiaofficial",
    isPurchased: true,
    notes: "Ukuran 38, payet mutiara halus",
  },
  {
    id: "ses-7",
    boxNumber: 4,
    boxName: "Box 4: Busana & Pakaian",
    name: "Kain Batik Tulis Sutra Motif Parang Barong",
    brand: "Batik Danar Hadi Solo",
    category: "Pakaian",
    estimatedPrice: 1800000,
    purchaseUrl: "https://danarhadistore.co.id",
    isPurchased: false,
    notes: "Kain batik panjang untuk bahan kebaya/sarimbit",
  },
];

export const mockPostWeddingItems: PostWeddingItem[] = [
  {
    id: "pw-1",
    name: "Kasur Springbed Orthopedic 160x200 (Queen Size)",
    roomCategory: "Kamar Tidur",
    brand: "Comforta Perfect Choice",
    price: 4850000,
    purchaseUrl: "https://shopee.co.id/search?keyword=comforta+perfect+choice+160",
    priority: "MUST_HAVE",
    isAcquired: true,
    isGiftClaimable: false,
    claimedBy: "Beli Mandiri Tabungan Bersama",
  },
  {
    id: "pw-2",
    name: "Kulkas 2 Pintu Inverter Smart Cooling 210L",
    roomCategory: "Dapur",
    brand: "LG GN-B215SQMT",
    price: 3550000,
    purchaseUrl: "https://tokopedia.com/search?q=kulkas+lg+2+pintu+inverter",
    priority: "MUST_HAVE",
    isAcquired: false,
    isGiftClaimable: true,
    claimedBy: "Sahabat Kampus Heru (Patungan 5 Orang)",
  },
  {
    id: "pw-3",
    name: "Mesin Cuci Front Loading 7.5 Kg Steam Wash",
    roomCategory: "Ruang Keluarga",
    brand: "Electrolux EWF7524D3WB",
    price: 5200000,
    purchaseUrl: "https://tokopedia.com/search?q=mesin+cuci+front+loading+electrolux",
    priority: "MUST_HAVE",
    isAcquired: false,
    isGiftClaimable: true,
  },
  {
    id: "pw-4",
    name: "Set Cookware Wajan Granit Anti Lengket 5 Pcs",
    roomCategory: "Dapur",
    brand: "Steincookware Glow Pan Series",
    price: 890000,
    purchaseUrl: "https://shopee.co.id/steincookware",
    priority: "MUST_HAVE",
    isAcquired: true,
    isGiftClaimable: true,
    claimedBy: "Mba Rina (Kakak Kandung Nurul)",
  },
  {
    id: "pw-5",
    name: "Smart Digital Rice Cooker Rendah Gula (Low Carbo)",
    roomCategory: "Dapur",
    brand: "Philips HD4515",
    price: 750000,
    purchaseUrl: "https://tokopedia.com/search?q=philips+hd4515",
    priority: "NICE_TO_HAVE",
    isAcquired: false,
    isGiftClaimable: true,
  },
  {
    id: "pw-6",
    name: "Smart TV 43 Inch 4K UHD Google TV",
    roomCategory: "Ruang Keluarga",
    brand: "Xiaomi TV A Pro 43",
    price: 3600000,
    purchaseUrl: "https://mi.co.id/id",
    priority: "DREAM_ITEM",
    isAcquired: false,
    isGiftClaimable: true,
  },
];

export const mockGuests: GuestItem[] = [
  {
    id: "g-1",
    name: "Bpk. H. Hendra Wijaya & Keluarga",
    side: "GROOM",
    category: "Keluarga Inti",
    pax: 4,
    phone: "081234567890",
    rsvpStatus: "CONFIRMED_ATTENDING",
    envelopeAmount: 1000000,
  },
  {
    id: "g-2",
    name: "Ibu Dra. Hj. Ratna Sari",
    side: "BRIDE",
    category: "Keluarga Inti",
    pax: 2,
    phone: "081398765432",
    rsvpStatus: "CONFIRMED_ATTENDING",
    envelopeAmount: 750000,
  },
  {
    id: "g-3",
    name: "Dimas Suryo, S.Kom (Rekan Kantor Tech Lead)",
    side: "GROOM",
    category: "Rekan Kantor",
    pax: 2,
    phone: "081987654321",
    rsvpStatus: "CONFIRMED_ATTENDING",
    envelopeAmount: 500000,
  },
  {
    id: "g-4",
    name: "Anisa Putri & Suami (Sahabat SMA Nurul)",
    side: "BRIDE",
    category: "Sahabat",
    pax: 2,
    phone: "085678901234",
    rsvpStatus: "CONFIRMED_ATTENDING",
    giftDescription: "Set Sprei King Koil Tencel",
  },
  {
    id: "g-5",
    name: "Prof. Dr. Ir. Gunawan Wibowo (Dosen Pembimbing)",
    side: "BOTH",
    category: "VIP",
    pax: 2,
    phone: "081122334455",
    rsvpStatus: "PENDING",
  },
];

export const mockRundown: RundownItem[] = [
  {
    id: "rd-1",
    startTime: "05:00",
    endTime: "07:30",
    activity: "Make Up & Rias Pengantin, Ibu, dan Bridesmaids",
    picName: "MUA Wardah Gallery & Bestie Nurul",
    picPhone: "081299887766",
    location: "Ruang Rias Utama Gedung",
    phase: "Akad Nikah",
  },
  {
    id: "rd-2",
    startTime: "07:30",
    endTime: "08:00",
    activity: "Penyambutan Rombongan Calon Pengantin Pria & Penyerahan Seserahan",
    picName: "Bpk. H. Sukardi (Juru Bicara)",
    picPhone: "081311223344",
    location: "Pintu Masuk Ruang Akad",
    phase: "Akad Nikah",
  },
  {
    id: "rd-3",
    startTime: "08:00",
    endTime: "09:00",
    activity: "Pelaksanaan Akad Nikah (Ijab Qabul, Khutbah Nikah, Tanda Tangan Buku Nikah)",
    picName: "Penghulu KUA Kec. Coblong & Saksi",
    picPhone: "081188990011",
    location: "Meja Akad Nikah",
    phase: "Akad Nikah",
  },
  {
    id: "rd-4",
    startTime: "09:00",
    endTime: "10:00",
    activity: "Prosesi Adat Sunda: Sungkeman, Saweran, Meuleum Harupat, & Pabetot Bakakak Hayam",
    picName: "Ki Lengser & Tim Sanggar Adat",
    picPhone: "087766554433",
    location: "Panggung Pelaminan",
    phase: "Adat & Sungkeman",
  },
  {
    id: "rd-5",
    startTime: "11:00",
    endTime: "14:00",
    activity: "Resepsi Pernikahan, Ramah Tamah, Hiburan Musik Akustik, & Foto Bersama Tamu",
    picName: "Wedding Organizer (WO Leader: Mas Arya)",
    picPhone: "081234567890",
    location: "Grand Ballroom",
    phase: "Resepsi Siang",
  },
];

export const mockFamilyQuota: FamilyQuota = {
  venueCapacity: 500,
  groomQuota: 125,
  brideQuota: 125,
  groomParentsQuota: 125,
  brideParentsQuota: 125,
  costPerPax: 85000,
};
